[project]
name = "dtc-ml-zoomcamp-2025-midterm-project"
version = "0.1.0"
description = "ML pipeline for predicting is wine excellent or not"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
